# Generated by Django 2.0 on 2018-08-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.CharField(max_length=16, verbose_name='文章代码')),
                ('article_name', models.CharField(max_length=64, verbose_name='文章标题')),
                ('article_author', models.CharField(max_length=16, verbose_name='文章作者')),
                ('article_time', models.DateField(max_length=16, verbose_name='发表时间')),
                ('article_name2', models.TextField(verbose_name='文章内容')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cataID', models.CharField(max_length=16, verbose_name='分类代码')),
                ('cata_name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('upcataID', models.CharField(max_length=16, verbose_name='上级分类代码')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
