# Generated by Django 2.0 on 2018-08-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='cata_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='upcataID',
            new_name='upperID',
        ),
    ]
