# Generated by Django 2.0 on 2018-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180822_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name2',
            field=models.CharField(max_length=64, verbose_name='文章副标题'),
        ),
    ]
