# Generated by Django 2.0 on 2018-08-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180822_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_name2',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_time',
            new_name='time',
        ),
    ]
