# Generated by Django 2.0 on 2018-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180822_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cataID',
            field=models.CharField(default=1, max_length=16, verbose_name='分类代码'),
            preserve_default=False,
        ),
    ]
