# Generated by Django 2.0 on 2018-09-06 01:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_cataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
